# Generated by Django 5.2.1 on 2025-07-11 08:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BalanceSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol_id", models.CharField(blank=True, max_length=80, null=True)),
                ("instrument_name", models.CharField(max_length=80)),
                (
                    "cash",
                    models.IntegerField(blank=True, null=True, verbose_name="وجه نقد"),
                ),
                (
                    "net_receivables",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="حساب های دریافتی"
                    ),
                ),
                (
                    "short_term_investments",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="سرمایه های کوتاه مدت"
                    ),
                ),
                (
                    "total_current_assets",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="دارایی های جاری "
                    ),
                ),
                (
                    "inventory",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="موجودی کالا"
                    ),
                ),
                (
                    "long_term_investments",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="سرمایه گذاری بلند مدت"
                    ),
                ),
                (
                    "property_plant_and_equipment",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="دادای های ثابت"
                    ),
                ),
                (
                    "intangible_assets",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="دارایی های نامشهود"
                    ),
                ),
                (
                    "total_assets",
                    models.IntegerField(blank=True, null=True, verbose_name="دارایی "),
                ),
                (
                    "accounts_payable",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="حساب های پرداختنی"
                    ),
                ),
                (
                    "total_current_liabilities",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="بدهی جاری "
                    ),
                ),
                (
                    "total_liabilities",
                    models.IntegerField(blank=True, null=True, verbose_name="بدهی"),
                ),
                (
                    "capital",
                    models.IntegerField(blank=True, null=True, verbose_name="سرمایه"),
                ),
                (
                    "retained_earnings",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="سود انباشته"
                    ),
                ),
                (
                    "equity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="حقوق صاحبان سرمایه"
                    ),
                ),
                (
                    "prepayment",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="پیش پرداخت"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol_id", models.CharField(blank=True, max_length=80, null=True)),
                ("instrument_name", models.CharField(max_length=80)),
                (
                    "total_income",
                    models.IntegerField(blank=True, null=True, verbose_name="فروش"),
                ),
                (
                    "gross_profit",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="سود ناخالص"
                    ),
                ),
                (
                    "operating_income_or_loss",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="سود عملیاتی"
                    ),
                ),
                (
                    "interest_expense",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="هزینه های مالی "
                    ),
                ),
                (
                    "income_before_tax",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="سود قبل از مالیات"
                    ),
                ),
                (
                    "net_income",
                    models.IntegerField(blank=True, null=True, verbose_name="سود خالص"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockWatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol_id", models.CharField(max_length=80)),
                ("instrument_name", models.CharField(max_length=80)),
                ("instrument_title", models.CharField(max_length=80)),
                (
                    "instrument_code",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "instrument_state_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "instrument_state_title",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("base_quantity", models.BigIntegerField(blank=True, null=True)),
                (
                    "pd1",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                ("zd1", models.IntegerField(blank=True, null=True)),
                ("qd1", models.BigIntegerField(blank=True, null=True)),
                (
                    "po1",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                ("zo1", models.IntegerField(blank=True, null=True)),
                ("qo1", models.BigIntegerField(blank=True, null=True)),
                (
                    "pd2",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                ("zd2", models.IntegerField(blank=True, null=True)),
                ("qd2", models.BigIntegerField(blank=True, null=True)),
                (
                    "po2",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                ("zo2", models.IntegerField(blank=True, null=True)),
                ("qo2", models.BigIntegerField(blank=True, null=True)),
                (
                    "pd3",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                ("zd3", models.IntegerField(blank=True, null=True)),
                ("qd3", models.BigIntegerField(blank=True, null=True)),
                (
                    "po3",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                ("zo3", models.IntegerField(blank=True, null=True)),
                ("qo3", models.BigIntegerField(blank=True, null=True)),
                ("buy_group_count", models.IntegerField(blank=True, null=True)),
                ("buy_group_volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "buy_group_volume_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("buy_firm_count", models.IntegerField(blank=True, null=True)),
                ("buy_firm_volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "buy_firm_volume_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("buy_individual_count", models.IntegerField(blank=True, null=True)),
                (
                    "buy_individual_volume",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "buy_individual_volume_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("sell_firm_count", models.IntegerField(blank=True, null=True)),
                ("sell_firm_volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "sell_firm_volume_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("sell_individual_count", models.IntegerField(blank=True, null=True)),
                (
                    "sell_individual_volume",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "sell_individual_volume_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "closing_price",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                (
                    "closing_price_variation",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                (
                    "closing_price_variation_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "exchange_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "exchange_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "last_trade_date",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "first_trade_price",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                (
                    "last_trade_price",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                (
                    "reference_price",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                (
                    "reference_price_variation",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                (
                    "reference_price_variation_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "year_highest_trade_price",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                (
                    "year_lowest_trade_price",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                (
                    "minimum_order_quantity",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "maximum_order_quantity",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "lower_price_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                (
                    "upper_price_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                (
                    "lowest_trade_price",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                (
                    "highest_trade_price",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                (
                    "previous_day_price",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                (
                    "total_number_of_shares_traded",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "total_number_of_trades",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("total_trade_value", models.BigIntegerField(blank=True, null=True)),
                ("eps", models.IntegerField(blank=True, null=True)),
                (
                    "price_per_earning_group",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "price_per_earning",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "free_float_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("month_average_volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "instrument_market_value",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "number_of_shares_or_bonds",
                    models.BigIntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ratio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol_id", models.CharField(blank=True, max_length=80, null=True)),
                ("instrument_name", models.CharField(max_length=80)),
                (
                    "current_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="جاری",
                    ),
                ),
                (
                    "quick_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="آنی",
                    ),
                ),
                (
                    "cash_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="نقد",
                    ),
                ),
                (
                    "da",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="بدهی (درصد)",
                    ),
                ),
                (
                    "de",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="بدهی به ح ص س",
                    ),
                ),
                (
                    "sa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="گردش دارای (بار)",
                    ),
                ),
                (
                    "accounts_receivable_turnover_ratio",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="دوره گردش دریافتنی (روز)"
                    ),
                ),
                (
                    "accounts_payable_turnover_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="حاشیه سود خالص (درصد)",
                    ),
                ),
                (
                    "inventory_turnover_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="دوره گردش موحودی ",
                    ),
                ),
                (
                    "profit_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="حاشیه سود خالص (درصد)",
                    ),
                ),
                (
                    "gross_profit_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="حاشیه سود ناخالص (درصد)",
                    ),
                ),
                (
                    "ebit_gross_profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="سود عملیاتی به سود ناخالص (درصد)",
                    ),
                ),
                (
                    "r_ebit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="هزینه بهره به سود عملیاتی (درصد)",
                    ),
                ),
                (
                    "roa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="بازده دارایی (درصد)",
                    ),
                ),
                (
                    "roe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="بازده ح ص س (درصد)",
                    ),
                ),
                (
                    "stock_watch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.stockwatch",
                        verbose_name="سهم ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketWatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance_sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.balancesheet",
                    ),
                ),
                (
                    "income",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.income",
                    ),
                ),
                (
                    "ratio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.ratio",
                    ),
                ),
                (
                    "stock_watch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.stockwatch",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="income",
            name="stock_watch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="data.stockwatch",
                verbose_name="سهم ",
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="stock_watch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="data.stockwatch",
                verbose_name="سهم ",
            ),
        ),
    ]
