# Generated by Django 1.10 on 2020-12-14 15:11
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockwatch",
            name="BaseQuantity",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="BuyFirmCount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="BuyFirmVolume",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="BuyFirmVolumePercentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="BuyGroupCount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="BuyGroupVolume",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="BuyGroupVolumePercentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="BuyIndividualCount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="BuyIndividualVolume",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="BuyIndividualVolumePercentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="ClosingPrice",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="ClosingPriceVariation",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="ClosingPriceVariationPercent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="CompanyName",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="Eps",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="ExchangeCode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="ExchangeName",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="FirstTradePrice",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="FreeFloatPercent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="HighestTradePrice",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="InstrumentCode",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="InstrumentMarketValue",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="InstrumentStateCode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="InstrumentStateTitle",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="LastTradeDate",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="LastTradePrice",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="LowerPriceThreshold",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="LowestTradePrice",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="MaximumOrderQuantity",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="MinimumOrderQuantity",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="MonthAverageVolume",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="NumberOfSharesOrBonds",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="PreviousDayPrice",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="PricePerEarning",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="PricePerEarningGroup",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="ReferencePrice",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="ReferencePriceVariation",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="ReferencePriceVariationPercent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="SellFirmCount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="SellFirmVolume",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="SellFirmVolumePercentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="SellIndividualCount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="SellIndividualVolume",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="SellIndividualVolumePercentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="TotalNumberOfSharesTraded",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="TotalNumberOfTrades",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="TotalTradeValue",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="UpperPriceThreshold",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="YearHighestTradePrice",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="YearLowestTradePrice",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="pd1",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="pd2",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="pd3",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="po1",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="po2",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="po3",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="qd1",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="qd2",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="qd3",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="qo1",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="qo2",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="qo3",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="zd1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="zd2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="zd3",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="zo1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="zo2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockwatch",
            name="zo3",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
