# Generated by Django 1.10 on 2020-12-14 12:08
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_auto_20201214_1308"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "token",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "refId",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "saleRefId",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "takingDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("success", models.BooleanField(default=False)),
                (
                    "failureerror",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.Membership",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت ها",
            },
        ),
    ]
