# Generated by Django 5.2.1 on 2025-07-11 08:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=11, verbose_name="نام پکیج")),
                ("category", models.CharField(blank=True, max_length=11, null=True)),
                ("price", models.FloatField(blank=True, default=0, null=True)),
                ("month_price", models.FloatField(blank=True, default=0, null=True)),
                ("gas_fee", models.FloatField(blank=True, default=0)),
                ("limit", models.FloatField(blank=True, default=1, null=True)),
                ("days", models.IntegerField(blank=True, default=30, null=True)),
                ("active", models.BooleanField(null=True)),
                ("description", models.TextField(blank=True, default="", null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(blank=True, default="", max_length=80, null=True),
                ),
                ("amount", models.FloatField(blank=True, default=0, null=True)),
                (
                    "reason",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "insert_time",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "txid",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expiry",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales.package",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
