# Generated by Django 1.10 on 2021-04-29 14:14
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_auto_20210429_1844"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=11, verbose_name="نام پکیج"),
                ),
                (
                    "category",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                ("price", models.FloatField(blank=True, default=0, null=True)),
                (
                    "days",
                    models.IntegerField(blank=True, default=30, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expiry", models.DateTimeField(blank=True, null=True)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales.Package",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.Profile",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="payment",
            name="membership",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
