# Generated by Django 1.10 on 2021-04-29 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_auto_20210429_1844"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="scan_fee",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
