# Generated by Django 1.10 on 2021-05-01 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_auto_20210429_2119"),
    ]

    operations = [
        migrations.RenameField(
            model_name="package",
            old_name="scan_fee",
            new_name="gas_fee",
        ),
    ]
