# Generated by Django 1.10 on 2021-05-01 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20210501_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='active',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='limit',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
