# Generated by Django 1.10 on 2021-05-01 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_auto_20210501_2153"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="month_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
