# Generated by Django 1.10 on 2021-05-02 08:06
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_package_month_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="expiry",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
