# Generated by Django 4.2.7 on 2023-11-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0010_payment_txid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="active",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
