version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "conda run -n xtrader-env python manage.py wait_for_db &&
             conda run -n xtrader-env python manage.py collectstatic --noinput &&
             conda run -n xtrader-env python manage.py makemigrations &&
             conda run -n xtrader-env python manage.py migrate &&
             conda run -n xtrader-env python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./xtrader:/xtrader
      - ./xtrader/migrations:/xtrader/migrations
      - ./xtrader/media:/vol/web/media
      - ./xtrader/static:/vol/web/static
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    networks:
      - xtrader-net

  db:
    image: postgres:17.4
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - xtrader-net

volumes:
  postgres_data:
  static_volume:
  media_volume:


networks:
  xtrader-net:
    driver: bridge
