# Generated by Django 5.2 on 2025-05-22 08:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='myExchange', max_length=80)),
                ('exchange', models.CharField(default='BINANCE', max_length=80)),
                ('public', models.CharField(blank=True, max_length=500, null=True)),
                ('private', models.CharField(blank=True, max_length=500, null=True)),
                ('trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook', models.CharField(blank=True, max_length=80, null=True)),
                ('trading', models.BooleanField(default=False)),
                ('notification', models.BooleanField(default=False)),
                ('trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(default=' استراتژی من ', max_length=80)),
                ('filters', models.TextField()),
                ('config', models.CharField(blank=True, max_length=500, null=True)),
                ('interval', models.CharField(blank=True, default='4h', max_length=5, null=True)),
                ('trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trader', to=settings.AUTH_USER_MODEL)),
                ('watch_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.watchlist')),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.watchlist')),
            ],
        ),
    ]
