# Generated by Django 5.2.1 on 2025-07-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exchange",
            name="exchange",
        ),
        migrations.AddField(
            model_name="exchange",
            name="type",
            field=models.CharField(
                choices=[("BIN", "Binance"), ("KC", "KuCoin"), ("CB", "Coinbase")],
                default="BIN",
                max_length=20,
            ),
        ),
    ]
