# Generated by Django 5.2.1 on 2025-09-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_remove_exchange_exchange_exchange_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exchange",
            old_name="private",
            new_name="private_key",
        ),
        migrations.RenameField(
            model_name="exchange",
            old_name="public",
            new_name="public_key",
        ),
        migrations.AlterField(
            model_name="exchange",
            name="name",
            field=models.CharField(default="myExchange", max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="type",
            field=models.CharField(
                choices=[("BI", "Binance"), ("KC", "KuCoin"), ("CB", "Coinbase")],
                default="BI",
                max_length=20,
            ),
        ),
    ]
