# Generated by Django 5.2.1 on 2025-07-11 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProTrader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_url", models.CharField(blank=True, max_length=80, null=True)),
                ("page_kind", models.CharField(blank=True, max_length=50, null=True)),
                ("brand", models.CharField(blank=True, max_length=12)),
                ("subscription", models.FloatField(blank=True, default=0)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("nav", models.IntegerField(blank=True, null=True)),
                ("beta", models.FloatField(blank=True, null=True)),
                ("one_year_performance", models.FloatField(blank=True, null=True)),
                ("six_months_performance", models.FloatField(blank=True, null=True)),
                ("three_months_performance", models.FloatField(blank=True, null=True)),
                ("one_months_performance", models.FloatField(blank=True, null=True)),
                ("total_performance", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "trader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expiry", models.DateTimeField()),
                (
                    "follower",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pro_trader",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social.protrader",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TraderHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_time", models.IntegerField(blank=True, default=0, null=True)),
                ("btc", models.FloatField(blank=True, default=0, null=True)),
                ("nav", models.FloatField(blank=True, default=0, null=True)),
                (
                    "trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social.protrader",
                    ),
                ),
            ],
        ),
    ]
