# Generated by Django 1.10 on 2020-12-28 15:22
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Protrader",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_url",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "page_kind",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("subscription", models.FloatField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("nav", models.IntegerField(blank=True, null=True)),
                ("beta", models.FloatField(blank=True, null=True)),
                (
                    "one_year_performace",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "six_months_performace",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "three_months_performace",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "one_months_performace",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "total_performance",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "trader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
