# Generated by Django 1.10 on 2021-01-01 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protrader',
            old_name='one_months_performace',
            new_name='one_months_performance',
        ),
        migrations.RenameField(
            model_name='protrader',
            old_name='one_year_performace',
            new_name='one_year_performance',
        ),
        migrations.RenameField(
            model_name='protrader',
            old_name='six_months_performace',
            new_name='six_months_performance',
        ),
        migrations.RenameField(
            model_name='protrader',
            old_name='three_months_performace',
            new_name='three_months_performance',
        ),
    ]
