# Generated by Django 1.10 on 2021-05-21 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20210101_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.IntegerField(blank=True, default=0, null=True)),
                ('btc', models.FloatField(blank=True, default=0, null=True)),
                ('nav', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='protrader',
            name='status',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='protrader',
            name='subscription',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='traderhistory',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Protrader'),
        ),
    ]
