# Generated by Django 1.10 on 2021-05-22 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20210521_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='expiry',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
