# Generated by Django 5.2 on 2025-05-10 13:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_hash', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
                'unique_together': {('storage_hash', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_hash', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='easy_thumbnails.source')),
            ],
            options={
                'unique_together': {('storage_hash', 'name', 'source')},
            },
        ),
        migrations.CreateModel(
            name='ThumbnailDimensions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(null=True)),
                ('height', models.PositiveIntegerField(null=True)),
                ('thumbnail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='easy_thumbnails.thumbnail')),
            ],
        ),
    ]
