# Generated by Django 5.2.1 on 2025-07-11 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_fee", models.FloatField(blank=True, default=0.01)),
                ("redeem_fee", models.FloatField(blank=True, default=0.01)),
                ("fee", models.FloatField(blank=True, default=0)),
                ("aum", models.FloatField(blank=True, default=0)),
                ("last_update", models.FloatField(blank=True, default=0, null=True)),
                ("brand", models.CharField(blank=True, default="", max_length=80)),
                ("deposit", models.FloatField(blank=True, default=0)),
                ("withdraw", models.FloatField(blank=True, default=0)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FundInvestor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nationalCode",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                (
                    "phoneNumber",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                ("first_name", models.CharField(blank=True, default="", max_length=20)),
                ("last_name", models.CharField(blank=True, default="", max_length=20)),
                (
                    "note",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                ("units", models.FloatField(blank=True, default=0, null=True)),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aum.fund"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FundUnitSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.CharField(blank=True, max_length=20, null=True)),
                ("quantity", models.FloatField(blank=True, default=0, null=True)),
                ("value", models.FloatField(blank=True, default=0, null=True)),
                ("nav", models.FloatField(blank=True, default=0, null=True)),
                ("ratio", models.FloatField(blank=True, default=0, null=True)),
                ("insert_date", models.DateField(blank=True, default=None, null=True)),
                ("age", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aum.fund"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnitTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(blank=True, max_length=12, null=True)),
                ("time", models.DateTimeField(blank=True, null=True)),
                ("units", models.FloatField(blank=True, default=0, null=True)),
                ("nav", models.FloatField(blank=True, default=0, null=True)),
                ("value", models.FloatField(blank=True, default=0, null=True)),
                ("commission", models.FloatField(blank=True, default=0, null=True)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aum.fundinvestor",
                    ),
                ),
            ],
        ),
    ]
