# Generated by Django 1.10 on 2021-03-22 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fund",
            name="brand",
            field=models.CharField(
                blank=True, default="", max_length=80, null=True
            ),
        ),
    ]
