# Generated by Django 5.2.1 on 2025-09-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aum", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fund",
            old_name="withdraw",
            new_name="withdrawal",
        ),
        migrations.RenameField(
            model_name="fundinvestor",
            old_name="nationalCode",
            new_name="national_code",
        ),
        migrations.RenameField(
            model_name="fundinvestor",
            old_name="phoneNumber",
            new_name="phone_number",
        ),
        migrations.AlterField(
            model_name="fundinvestor",
            name="units",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
