# Generated by Django 1.10 on 2021-03-24 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0003_auto_20210323_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='units',
        ),
    ]
