# Generated by Django 1.10 on 2021-04-15 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0004_remove_fund_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundUnitSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.FloatField(blank=True, default=0, null=True)),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('ratio', models.FloatField(blank=True, default=0, null=True)),
                ('insert_date', models.DateField(blank=True, default=None, null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aum.Fund')),
            ],
        ),
    ]
