# Generated by Django 1.10 on 2021-04-15 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aum', '0005_fundunitsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundunitsnapshot',
            name='nav',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
