# Generated by Django 1.10 on 2020-12-14 05:28
from __future__ import unicode_literals

import datetime
from datetime import timezone

import django.db.models.deletion
import easy_thumbnails.fields
import userena.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mugshot",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True,
                        help_text="A personal image displayed in your profile.",
                        upload_to=userena.models.upload_to_mugshot,
                        verbose_name="mugshot",
                    ),
                ),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("registered", "Registered"),
                            ("closed", "Closed"),
                        ],
                        default="registered",
                        help_text="Designates who can view your profile.",
                        max_length=15,
                        verbose_name="privacy",
                    ),
                ),
                (
                    "cellPhone",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        verbose_name="شماره تلفن ",
                    ),
                ),
                (
                    "expire",
                    models.DateField(
                        default=datetime.datetime(
                            2020,
                            12,
                            24,
                            5,
                            28,
                            10,
                            760313,
                            tzinfo=timezone.utc,
                        )
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "permissions": (("view_profile", "Can view profile"),),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=11, verbose_name="نام پکیج"),
                ),
                ("price", models.IntegerField()),
                ("value", models.IntegerField()),
                ("vip", models.BooleanField(default=0, verbose_name="ویژه")),
            ],
        ),
        migrations.AddField(
            model_name="membership",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.Profile",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="subscribe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.Subscribe",
            ),
        ),
    ]
