# Generated by Django 5.2.1 on 2025-07-11 08:15

import django.db.models.deletion
import easy_thumbnails.fields
import userena.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mugshot",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True,
                        help_text="A personal image displayed in your profile.",
                        upload_to=userena.models.upload_to_mugshot,
                        verbose_name="mugshot",
                    ),
                ),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("registered", "Registered"),
                            ("closed", "Closed"),
                        ],
                        default="registered",
                        help_text="Designates who can view your profile.",
                        max_length=15,
                        verbose_name="privacy",
                    ),
                ),
                (
                    "cellPhone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="شماره تلفن "
                    ),
                ),
                ("expire", models.DateField(blank=True, null=True)),
                ("telegram_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "telegram_activation_code",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                (
                    "telegram_activation_timestamp",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "referral_code",
                    models.CharField(blank=True, default="", max_length=80, null=True),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "permissions": (("view_profile", "Can view profile"),),
                "abstract": False,
                "default_permissions": ("add", "change", "delete"),
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.FloatField(default=0)),
                ("income", models.FloatField(blank=True, default=0, null=True)),
                (
                    "address",
                    models.CharField(blank=True, default="", max_length=80, null=True),
                ),
                (
                    "nonce",
                    models.CharField(blank=True, default="", max_length=40, null=True),
                ),
                ("last_change", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_in",
                    models.CharField(blank=True, default="", max_length=80, null=True),
                ),
                (
                    "address_out",
                    models.CharField(blank=True, default="", max_length=80, null=True),
                ),
                (
                    "txid_in",
                    models.CharField(blank=True, default="", max_length=80, null=True),
                ),
                (
                    "txid_out",
                    models.CharField(blank=True, default="", max_length=80, null=True),
                ),
                ("init_amount", models.FloatField(blank=True, default=0, null=True)),
                ("final_amount", models.FloatField(blank=True, default=0, null=True)),
                (
                    "result",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                (
                    "coin",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                (
                    "network",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                ("tx_time", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.wallet",
                    ),
                ),
            ],
        ),
    ]
