# Generated by Django 5.2.1 on 2025-09-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallet",
            old_name="last_change",
            new_name="updated_at",
        ),
        migrations.AlterField(
            model_name="deposit",
            name="address_in",
            field=models.CharField(default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="address_out",
            field=models.CharField(default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="final_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="init_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="txid_in",
            field=models.CharField(default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="txid_out",
            field=models.CharField(default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="address",
            field=models.CharField(default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="income",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="nonce",
            field=models.CharField(default="", max_length=40),
        ),
    ]
