# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-12-14 15:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from datetime import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201214_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expire',
            field=models.DateField(default=datetime.datetime(2020, 12, 24, 15, 11, 9, 40234, tzinfo=timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
