# Generated by Django 1.10 on 2020-12-15 17:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from datetime import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201214_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expire',
            field=models.DateField(default=datetime.datetime(2020, 12, 25, 17, 15, 53, 690462, tzinfo=timezone.utc)),
        ),
    ]
