# Generated by Django 1.10 on 2020-12-17 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from datetime import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201215_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expire',
            field=models.DateField(default=datetime.datetime(2020, 12, 27, 13, 54, 7, 560056, tzinfo=timezone.utc)),
        ),
    ]
