# Generated by Django 1.10 on 2020-12-17 14:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from datetime import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201217_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expire',
            field=models.DateField(default=datetime.datetime(2020, 12, 27, 14, 5, 26, 578021, tzinfo=timezone.utc)),
        ),
    ]
