# Generated by Django 1.10 on 2020-12-21 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_auto_20201217_1507"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="telegram_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
