# Generated by Django 1.10 on 2020-12-23 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_activation_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_activation_timestamp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
