# Generated by Django 1.10 on 2020-12-23 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201223_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_activation_timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
