# Generated by Django 1.10 on 2021-01-09 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_auto_20201223_1402"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cellPhone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="شماره تلفن ",
            ),
        ),
    ]
