# Generated by Django 1.10 on 2021-04-16 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_auto_20210109_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('amount_out', models.FloatField(blank=True, default=0, null=True)),
                ('tx_out', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('tx_time', models.IntegerField(blank=True, default=time.time, null=True)),
                ('tx_id', models.CharField(blank=True, default='', max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('nonce', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('last_change', models.IntegerField(blank=True, default=time.time, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transactions',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Wallet'),
        ),
    ]
