# Generated by Django 1.10 on 2021-04-17 12:22
from __future__ import unicode_literals

import time

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_auto_20210416_1943"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_in",
                    models.CharField(
                        blank=True, default="", max_length=80, null=True
                    ),
                ),
                (
                    "address_out",
                    models.CharField(
                        blank=True, default="", max_length=80, null=True
                    ),
                ),
                (
                    "txid_in",
                    models.CharField(
                        blank=True, default="", max_length=80, null=True
                    ),
                ),
                (
                    "txid_out",
                    models.CharField(
                        blank=True, default="", max_length=80, null=True
                    ),
                ),
                (
                    "init_amount",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "final_amount",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True, default="", max_length=20, null=True
                    ),
                ),
                (
                    "coin",
                    models.CharField(
                        blank=True, default="", max_length=10, null=True
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        blank=True, default="", max_length=10, null=True
                    ),
                ),
                (
                    "tx_time",
                    models.IntegerField(
                        blank=True, default=time.time, null=True
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.Wallet",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="transactions",
            old_name="tx_out",
            new_name="txid_out",
        ),
        migrations.AlterField(
            model_name="transactions",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.Wallet",
            ),
        ),
    ]
