# Generated by Django 1.10 on 2021-04-17 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_auto_20210417_1652"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactions",
            name="wallet",
        ),
        migrations.DeleteModel(
            name="Transactions",
        ),
    ]
