# Generated by Django 1.10 on 2021-04-29 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_auto_20210418_1029"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="subscribe",
        ),
    ]
