# Generated by Django 1.10 on 2021-04-29 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_auto_20210429_1844"),
        ("sales", "0002_auto_20210429_1844"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Membership",
        ),
        migrations.DeleteModel(
            name="Subscribe",
        ),
    ]
