# Generated by Django 1.10 on 2021-05-11 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_wallet_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
    ]
