# Generated by Django 4.2.7 on 2023-11-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_auto_20210511_1048"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (("view_profile", "Can view profile"),),
            },
        ),
    ]
